# Generated by Django 6.0.6 on 2026-07-07 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='workspacemember',
            name='joined_at',
        ),
        migrations.RemoveField(
            model_name='workspacemember',
            name='role',
        ),
        migrations.CreateModel(
            name='WorkspacePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to='workspaces.workspace')),
            ],
            options={
                'unique_together': {('workspace', 'user')},
            },
        ),
    ]
