# Generated by Django 6.0.6 on 2026-07-07 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0002_remove_workspace_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workspace",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_workspaces",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workspacemember",
            name="joined_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workspacemember",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("member", "Member"),
                ],
                default="member",
                max_length=20,
            ),
        ),
    ]