# Generated by Django 6.0.6 on 2026-07-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_workspace_created_at_workspace_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacepresence',
            name='current_room',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
